# Generated by Django 4.2.11 on 2025-02-27 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=11)),
                ('category', models.CharField(choices=[('infrastructure', 'Infrastructure & Maintenance'), ('waste', 'Waste Management & Recycling'), ('safety', 'Public Safety & Crime'), ('noise', 'Noise & Environmental Nuisances'), ('traffic', 'Parking & Traffic Issues'), ('housing', 'Housing & Property Concerns'), ('transport', 'Public Transport Complaints'), ('parks', 'Green Spaces & Parks'), ('water', 'Water & Sewage Issues'), ('licensing', 'Licensing & Regulatory Complaints'), ('animals', 'Animal-Related Concerns'), ('accessibility', 'Accessibility & Disability Issues'), ('health', 'Public Health & Hygiene'), ('council', 'Council Services & Administration'), ('other', 'Other')], default='infrastructure', max_length=50)),
                ('subcategory', models.CharField(blank=True, max_length=50)),
                ('issue_description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reference_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('validated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('Complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='complaintsapp.submittedissue')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
