# Generated by Django 4.2.11 on 2025-02-27 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaintsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittedissue',
            name='reference_id',
        ),
    ]
