# Generated by Django 4.2.11 on 2025-02-27 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaintsapp', '0002_remove_submittedissue_reference_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activeissue',
            old_name='Complaint',
            new_name='complaint',
        ),
    ]
